blueprint:
  name: Motion-activated Light with Sunset Condition
  description: Turn on a light when motion is detected, only between sunset and sunrise. Prolong countdown if motion reoccurs.
  domain: automation
  source_url: https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/motion_light.yaml
  author: Home Assistant
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

# Restart mode ensures the automation restarts on new triggers.
mode: restart
max_exceeded: silent

triggers:
  - platform: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"

# Conditions ensure the automation only runs during the specified time period.
conditions:
  - condition: sun
    after: sunset
    before: sunrise

actions:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      - platform: state
        entity_id: !input motion_entity
        from: "on"
        to: "off"
    timeout: !input no_motion_wait
    continue_on_timeout: true
  - alias: "Turn off the light if no motion detected"
    condition: template
    value_template: "{{ is_state(!input motion_entity, 'off') }}"
    service: light.turn_off
    target: !input light_target
